default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-builtin-literals
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: name-tests-test
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  # - repo: https://github.com/pycqa/isort
  #   rev: 5.12.0
  #   hooks:
  #     - id: isort

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.7.0
    hooks:
      - id: pyupgrade
        args: [--py311-plus]

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
        exclude: ^docs/conf.py
        additional_dependencies:
          - types-dataclasses >= 0.1.3
          - types-PyYAML
          - tomli >= 0.2.6, < 2.0.0
          - types-typed-ast >= 1.4.1
          - click >= 8.1.0
          - packaging >= 22.0
          - platformdirs >= 2.1.0
          - pytest
          - hypothesis
          - django-stubs[compatible-mypy]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.275
    hooks:
      - id: ruff

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit

  # - repo: https://github.com/codespell-project/codespell
  #   rev: v2.2.4
  #   hooks:
  #     - id: codespell
  #       additional_dependencies:
  #         - tomli
